### ISSUE TITLE
Issue with Linux

### ISSUE THREAD

**Issue by bkkhanny** [isuruwa/AUTOZOOM-BOT#1]
Can't run the script with linux because of encoding issues. It says "syntax error non utf8 code" ~ works fine or Windows.

**Comment by isuruwa** [comment]
Still Script is supported for only windows  . Expect a linux supported update in  future .

**Comment by bkkhanny** [comment]
Are you willing to share sourcecode? Looks to be hard coded. Needing it ASAP

**Comment by isuruwa** [comment]
I can't make source code public for now . But , I will make it soon .
